version: '3.4'

services:
  pacote:
    image: pacote
    build:
      context: node_modules/pacote
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "lib/index.js"]
